DROP TABLE VERIFICATION.CCAA_REDEEMED;

CREATE SEQUENCE VERIFICATION.SQ_NM_ID_CCAA_KPI;

CREATE TABLE VERIFICATION.CCAA_KPI (
    NM_ID_CCAA_KPI        INTEGER DEFAULT nextval('VERIFICATION.SQ_NM_ID_CCAA_KPI'),
    NM_VERSION            INTEGER DEFAULT 0,
    FC_CREATION_DATE      TIMESTAMP DEFAULT now() NOT NULL,
    FC_UPDATE_DATE        TIMESTAMP DEFAULT NULL,
    DE_CCAA_ID            CHAR (2) NOT NULL,
    IN_CCAA_CREATION      BOOLEAN DEFAULT TRUE NOT NULL,
    FC_KPI_DATE           DATE NOT NULL,
    DE_KPI_TYPE           CHAR VARYING (25) NOT NULL,
    NM_KPI_VALUE          INTEGER DEFAULT 0 NOT NULL,
    CONSTRAINT PK_CCAA_KPI
        PRIMARY KEY (NM_ID_CCAA_KPI),
    CONSTRAINT UNQ_CCAA_KPI_CCAA_DATE_TYPE
        UNIQUE (DE_CCAA_ID, FC_KPI_DATE, DE_KPI_TYPE),
    CONSTRAINT FK_CCAA_KPI_CCAA
        FOREIGN KEY (DE_CCAA_ID)
            REFERENCES VERIFICATION.CCAA (DE_CCAA_ID)
);

ALTER SEQUENCE VERIFICATION.SQ_NM_ID_CCAA_KPI
    OWNED BY VERIFICATION.CCAA_KPI.NM_ID_CCAA_KPI;

CREATE INDEX IN_VERIFICATION_CCAA_KPI_DATE_KPI
    ON VERIFICATION.CCAA_KPI(FC_KPI_DATE, DE_KPI_TYPE);

CREATE INDEX IN_VERIFICATION_CCAA_KPI_CCAA_TYPE
    ON VERIFICATION.CCAA_KPI(DE_CCAA_ID, DE_KPI_TYPE);

