CREATE SEQUENCE VERIFICATION.SQ_NM_ID_CCAA_AUTH;

CREATE TABLE VERIFICATION.CCAA_AUTH
(
    NM_ID_CCAA_AUTH  INTEGER DEFAULT nextval('VERIFICATION.SQ_NM_ID_CCAA_AUTH'),
    NM_VERSION       INTEGER DEFAULT 0,
    FC_CREATION_DATE TIMESTAMP DEFAULT now() NOT NULL,
    DE_CCAA_ID       CHAR (2) NOT NULL,
    DE_AUTH          CHAR VARYING (25) NOT NULL,
    CONSTRAINT PK_CCAA_AUTH
        PRIMARY KEY (NM_ID_CCAA_AUTH),
    CONSTRAINT UNQ_CCAA_AUTH
        UNIQUE (DE_CCAA_ID, DE_AUTH),
    CONSTRAINT FK_CCAA_AUTH_CCAA
        FOREIGN KEY (DE_CCAA_ID)
            REFERENCES VERIFICATION.CCAA (DE_CCAA_ID)
);

ALTER SEQUENCE VERIFICATION.SQ_NM_ID_CCAA_AUTH
    OWNED BY VERIFICATION.CCAA_AUTH.NM_ID_CCAA_AUTH;

CREATE INDEX IN_VERIFICATION_CCAA_AUTH_CCAA
    ON VERIFICATION.CCAA_AUTH (DE_CCAA_ID);
