server:
  port: 8080
management:
  server:
    port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/RADARCOVID?schema=verification
    username: radarcovid
    password: radarcovid
  jpa:
    properties:
      hibernate:
        default_schema: verification

application:
  log.enabled: false
  jwt:
    subject: 99
    issuer: RadarCOVID
  credentials:
    # NOT REAL CREDENTIALS
    privateKey: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSHVBZ0VBTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFqQklIV01JSFRBZ0VCQkVJQkEvVmRTM21lWEFkQ0ZhdmoKQ2t4dGxPbnErT1lNSUlHQVlSQW9vYnRCRDdpV2ZhT2xYZ1UvaU9mdVRjaG5GZ0txR1dSUGZJeUVFcmp3OEcrZQppbGJQSGlDaGdZa0RnWVlBQkFGdkF5bXl5bE00UEVnaFg5SzZXV0JMaE5OamNCVi9ycjVvZlpVSlpsb0xlTG1pCkIrcWpZNUVnSkNGOGJyVEJVUE81S01FRWhtTHJXWlhBRExtcXRNb2R1Z0RFTFdLdHVjeGZ5aVJENXFOOFliL2cKOHl2Mk9GT29tT0xkeThMSTNVQi9vUi91QW5OY3BGcGQrNXFzdE14UitoWnhiWWhpa1QyMDBpemNjdDgrRGNldQpJUT09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K"
    publicKey: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHYk1CQUdCeXFHU000OUFnRUdCU3VCQkFBakE0R0dBQVFCYndNcHNzcFRPRHhJSVYvU3VsbGdTNFRUWTNBVgpmNjYrYUgyVkNXWmFDM2k1b2dmcW8yT1JJQ1FoZkc2MHdWRHp1U2pCQklaaTYxbVZ3QXk1cXJUS0hib0F4QzFpCnJibk1YOG9rUSthamZHRy80UE1yOWpoVHFKamkzY3ZDeU4xQWY2RWY3Z0p6WEtSYVhmdWFyTFRNVWZvV2NXMkkKWXBFOXROSXMzSExmUGczSHJpRT0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="
  dummy:
    enabled: true
    ccaa: DUMMY
    # NOT REAL CREDENTIALS
    privateKey: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSHVBZ0VBTUJBR0J5cUdTTTQ5QWdFR0JTdUJCQUFqQklIV01JSFRBZ0VCQkVJQTVvRVgvV0srNG1PZlZFK0gKWXVXN2RCUEsvV1JXYS80dGFBU0YxVkx1UHMyMVltVE9BQzdyamk0WmdZWk9scXNVYTc3VndXYmVJZ1RKR25KeAo5bnZhdDNDaGdZa0RnWVlBQkFBYjExQTl1VHdnamJpSnFNOGdvUEJCTmd1eHNkaHkxMTN4SzlFY2lpMUQybjA4Ck5KazloNDc0bzhhU0tFWUpTSnd6MmphL1gzZ2RMV0tPNmhOWmhxcWdDZ0V1dHEzQWh3WTJOOXRXOXZwVFJTbzAKTklCRW9wTEh2SkdOaVU1NEZ6c3V2dDJ3Z3ZrNFY2N2t4UUtJT2JNRkdnaVVWVERLWTBmQ0V0cWFJcW9RdE5qYgovdz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K"
    publicKey: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHYk1CQUdCeXFHU000OUFnRUdCU3VCQkFBakE0R0dBQVFBRzlkUVBiazhJSTI0aWFqUElLRHdRVFlMc2JIWQpjdGRkOFN2UkhJb3RROXA5UERTWlBZZU8rS1BHa2loR0NVaWNNOW8ydjE5NEhTMWlqdW9UV1lhcW9Bb0JMcmF0CndJY0dOamZiVnZiNlUwVXFORFNBUktLU3g3eVJqWWxPZUJjN0xyN2RzSUw1T0ZldTVNVUNpRG16QlJvSWxGVXcKeW1OSHdoTGFtaUtxRUxUWTIvOD0KLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg=="
