server:
  servlet:
    context-path: 

spring:
  sleuth:
    keys.http.headers: X-Amz-Cf-Id
    baggage:
      remote-fields: X-Amz-Cf-Id
      correlation-fields: X-Amz-Cf-Id

application:
  dummy:
    enabled: true
    ccaa: DUMMY
    privateKey: ${DUMMY_PRIVATE_KEY}
    publicKey: ${DUMMY_PUBLIC_KEY}

logging:
  pattern:
    console: '[%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} %c{1} - [%X{TRACKING}] [%X{X-B3-TraceId},%X{X-Amz-Cf-Id}] - %msg%n'
  level:
    root: info
    es.gob.radarcovid: debug

